### ISSUE TITLE
KeyError: 'timezone' in skill

### ISSUE THREAD

**Issue by hanzala123** [MycroftAI/skill-weather#179]
This is what i get when i call the weather skill.

2021-08-07 01:28:40.530 | ERROR    | 28447 | WeatherSkill | Unexpected error retrieving weather
Traceback (most recent call last):
  File "/opt/mycroft/skills/mycroft-weather.mycroftai/__init__.py", line 1098, in _get_weather
    self.config_core.get("system_unit"), latitude, longitude
  File "/opt/mycroft/skills/mycroft-weather.mycroftai/skill/api.py", line 106, in get_weather_for_coordinates
    local_weather = WeatherReport(response)
  File "/opt/mycroft/skills/mycroft-weather.mycroftai/skill/weather.py", line 247, in __init__
    timezone = report["timezone"]
KeyError: 'timezone'

**Comment by forslund** [comment]
I noticed the same thing earlier today. I printed the whole received message:
```python
{'cod': 401,
 'message': 'Invalid API key. Please see '
            'http://openweathermap.org/faq#error401 for more info.'}
```

It seems like there is a problem with the current API-key or something in the Backend that handles the communications with openweathermap. The skill should work once this is resolved.

**Comment by JarbasAl** [comment]
sounds like mycroft key has been revoked, one more reason to allow setting your own api keys locally

**Comment by krisgesling** [comment]
Hey @hanzala123 thanks for flagging this. We exceeded the API quota so have bumped it up to the next tier and it's back online.

As we continue to grow this scenario will continue to happen so I've also added a ticket for us to implement monitoring of these 3rd party API's. Then we can see when quota's are getting close, and have alerts if an API call stops returning a successful response for any reason, rather than being notified by the community or having tests fail.

Still very much agree with adding personal key setting either locally or via Skill settings.

Please let us know if anyone is still seeing this error.
